### ISSUE TITLE
Familiarize with the code

### ISSUE THREAD

**Issue by fedem-p** [fedem-p/BudgetApp2.0#2]
# Tasks

- [x] Read Readme
- [x] Install poetry
- [x] run the tests
- [x] run all the linting commands
- [x] run the app

**Comment by aishwarya0109** [comment]
Done
