### ISSUE TITLE
Write docstrings for functions

### ISSUE THREAD

**Issue by fedem-p** [fedem-p/BudgetApp2.0#3]
Write comprehensive docstrings like this one:

```python
def divide(a, b):
    """
    This function divides two numbers and returns the result.

    Args:
        a (float): The numerator.
        b (float): The denominator.

    Returns:
        float: The result of the division.

    Example:
        >>> divide(10.0, 2.0)
        5.0

    Raises:
        ZeroDivisionError: If the denominator is zero.

    Note:
        - This function performs division and returns a float result.
        - Make sure the denominator (b) is not zero to avoid a ZeroDivisionError.
    """
    if b == 0:
        raise ZeroDivisionError("Division by zero is not allowed.")
    return a / b
```

# Tasks

- [ ] this function https://github.com/fedem-p/BudgetApp2.0/blob/99612769d9d44b485324cb77d63f7c3fe9a3221b/budget-app/core/data_manager.py#L211
- [ ] this function https://github.com/fedem-p/BudgetApp2.0/blob/99612769d9d44b485324cb77d63f7c3fe9a3221b/budget-app/core/data_manager.py#L222
- [ ] this function https://github.com/fedem-p/BudgetApp2.0/blob/99612769d9d44b485324cb77d63f7c3fe9a3221b/budget-app/core/data_manager.py#L233
- [ ] this function https://github.com/fedem-p/BudgetApp2.0/blob/99612769d9d44b485324cb77d63f7c3fe9a3221b/budget-app/core/data_manager.py#L242
- [ ] this function https://github.com/fedem-p/BudgetApp2.0/blob/99612769d9d44b485324cb77d63f7c3fe9a3221b/budget-app/core/data_manager.py#L257
- [ ] this function https://github.com/fedem-p/BudgetApp2.0/blob/99612769d9d44b485324cb77d63f7c3fe9a3221b/budget-app/core/data_manager.py#L275

**Comment by fedem-p** [comment]
Closed by #20
